#ifndef SINGLEPP_MARKERS_HPP
#define SINGLEPP_MARKERS_HPP

#include <vector>

/**
 * @file Markers.hpp
 *
 * @brief Define the `Markers` typedef.
 */

namespace singlepp {

/**
 * A vector of vectors of ranked marker lists, used to determine which features should be used to compute correlations in `SinglePP`.
 *
 * For a `Markers` object `markers`, let us consider the vector at `markers[0][1]`.
 * This vector is expected to contain the ranked indices of the marker genes for label 0 compared to label 1.
 * Most typically, this is generated by identifying the genes that are upregulated in label 0 compared to 1 and sorting by decreasing effect size.
 * Indices should refer to the rows of the reference expression matrices (i.e., `ref` in the various `SinglePP::run` or `SinglePP::build` methods).
 * So, for example, `markers[0][1][0]` should contain the row index of the most upregulated gene in label 0 compared to 1.
 *
 * A given `Markers` object should have length equal to the number of labels.
 * Each middle vector (i.e., `markers[i]` for positive `i` less than the number of labels) should also have length equal to the number of labels.
 * Any innermost vector along the "diagonal" (i.e., `markers[i][i]`) is ignored and may be of zero length.
 * All other innermost vectors may be of any length and should contain unique indices.
 *
 * To be precise, the non-diagonal innermost vectors should be at least as long as the setting of `SinglePP::set_top()`.
 * The annotation will still work with shorter (non-empty) vectors but it will not be possible to achieve the user-specified `set_top()`.
 * In cases involving feature intersections in `run()`, the vectors should be long enough to achieve the specified `set_top()` after removing non-shared genes.
 * For longer vectors, the annotation will safely ignore the indices after the `set_top()` specification.
 */
typedef std::vector<std::vector<std::vector<int> > > Markers;

}

#endif
