df <- data.frame(
    Title = sprintf("Blueprint/Encode RNA-seq %s", c("logcounts", "colData")), # This can be the exact file name (if self-describing) or a more complete description.
    Description = sprintf("%s 259 RNA-seq samples of pure stroma and immune cells generated by Blueprint and ENCODE", 
        c("Matrix of log-normalized expression values from", "Per-sample metadata containing cell type labels of")),
    RDataPath = file.path("SingleR", "blueprint_encode","1.0.0", c("logcounts.rds", "coldata.rds")),
    BiocVersion="3.10", # The first Bioconductor version the resource was made available for.
    Genome=NA, # Can be NA.
    SourceType="RDA", #  Format of original data, e.g., FASTA, BAM, BigWig, etc. ‘getValidSourceTypes()’ for currently acceptable values
    SourceUrl="https://github.com/dviraran/SingleR/tree/master/data",
    SourceVersion="blueprint_encode.rda",
    Species="Homo sapiens", # getSpeciesList, validSpecies, or suggestSpecies(); can be NA
    TaxonomyId="9606",
    Coordinate_1_based=NA, #TRUE, FALSE, NA
    DataProvider="Blueprint and ENCODE",
    Maintainer="Friederike Duendar <frd2007@med.cornell.edu>",
    RDataClass="character", # R / Bioconductor class the data are stored in, e.g., GRanges, SummarizedExperiment, ExpressionSet etc.
    DispatchClass="Rds", # Determines how data are loaded into R.
    stringsAsFactors = FALSE
)

write.csv(file="../extdata/metadata-blueprint_encode.csv", df, row.names=FALSE)
