write.csv(file="../extdata/metadata-immgen.csv", 
          data.frame(
              Title = sprintf("ImmGen %s", c("logcounts", "colData")), # This can be the exact file name (if self-describing) or a more complete description.
              Description = sprintf("%s 830 microarray samples of sorted, mostly primary mouse immune cells generated by The Immunological Genome Project", 
                                    c("Matrix of normalized expression values from", "Per-sample metadata containing the cell type labels of")),
              RDataPath = file.path("SingleR", "immgen","1.0.0"), 
              c("logcounts.rds", "coldata.rds"),
              BiocVersion="3.10", # The first Bioconductor version the resource was made available for.
              Genome=NA, # Can be NA.
              SourceType="RDA", #  Format of original data, e.g., FASTA, BAM, BigWig, etc. ‘getValidSourceTypes()’ for currently acceptable values
              SourceUrl=c(
                  "https://github.com/dviraran/SingleR/tree/master/data",
                  "https://github.com/dviraran/SingleR/tree/master/data"
              ),
              SourceVersion=c(
                  "blueprint_encode.rda",
                  "blueprint_encode.rda"),
              Species="Mus musculus", # getSpeciesList, validSpecies, or suggestSpecies(); can be NA
              TaxonomyId="10090",
              Coordinate_1_based=NA, #TRUE, FALSE, NA
              DataProvider="ImmGen",
              Maintainer="Friederike Duendar <frd2007@med.cornell.edu>",
              RDataClass="character", # R / Bioconductor class the data are stored in, e.g., GRanges, SummarizedExperiment, ExpressionSet etc.
              DispatchClass="Rds", # Determines how data are loaded into R.
              stringsAsFactors = FALSE
          ),
          row.names=FALSE)
